# Generated by Django 6.0.6 on 2026-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-updated_at', '-id'], name='products_pr_updated_226cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-updated_at', '-id'], name='products_pr_categor_fbaabf_idx'),
        ),
    ]
